universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_active_learning.sh $(model) 42 cpu
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
output = results/active_learning_cgre_fixed_test/condor/$(model).$(ClusterId).$(ProcId).out
error = results/active_learning_cgre_fixed_test/condor/$(model).$(ClusterId).$(ProcId).err
log = results/active_learning_cgre_fixed_test/condor/cpu.$(ClusterId).log
queue model in aubin_1_10_1, mlp_small, mlp_deep
