universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_active_learning_finish.sh
should_transfer_files = NO
request_cpus = 1
request_memory = 1GB
request_disk = 1GB
output = results/active_learning_cgre_fixed_test/condor/finish.$(ClusterId).out
error = results/active_learning_cgre_fixed_test/condor/finish.$(ClusterId).err
log = results/active_learning_cgre_fixed_test/condor/finish.$(ClusterId).log
queue 1
