universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_active_learning.sh $(model) 42 cuda
should_transfer_files = NO
request_cpus = 1
request_memory = 8GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && (TARGET.GPUs_GlobalMemoryMb >= 16000)
output = results/active_learning_cgre_fixed_test/condor/$(model).$(ClusterId).$(ProcId).out
error = results/active_learning_cgre_fixed_test/condor/$(model).$(ClusterId).$(ProcId).err
log = results/active_learning_cgre_fixed_test/condor/gpu.$(ClusterId).log
queue model in CNN_Jannis_OHE, CNN_Jannis_ESM
