universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_esm_model.sh
arguments = all_mean $(fold) cpu
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 0
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de")
output = results/esm_cgreGFP/condor/mean_$(fold).$(ClusterId).out
error = results/esm_cgreGFP/condor/mean_$(fold).$(ClusterId).err
log = results/esm_cgreGFP/condor/mean.$(ClusterId).log
queue fold in holdout,00,01,02,03,04,05,06,07,08,09
