universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_esm_model.sh
arguments = $(model) $(fold) cuda
should_transfer_files = NO
request_cpus = 1
request_memory = 14GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && ((TARGET.GPUs_GlobalMemoryMb >= 30000) || (TARGET.GPUs_DeviceName == "NVIDIA GeForce RTX 2080 Ti"))
output = results/esm_cgreGFP/condor/$(model)_$(fold).$(ClusterId).$(ProcId).out
error = results/esm_cgreGFP/condor/$(model)_$(fold).$(ClusterId).$(ProcId).err
log = results/esm_cgreGFP/condor/cnn.$(ClusterId).log
queue model,fold from condor/esm_cnn_jobs.txt
