universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_jannis_ohe.sh
arguments = $(fold)
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && ((TARGET.GPUs_GlobalMemoryMb >= 30000) || (TARGET.GPUs_DeviceName == "NVIDIA GeForce RTX 2080 Ti"))
output = results/jannis_ohe_cgreGFP/condor/$(fold).$(ClusterId).$(ProcId).out
error = results/jannis_ohe_cgreGFP/condor/$(fold).$(ClusterId).$(ProcId).err
log = results/jannis_ohe_cgreGFP/condor/jobs.$(ClusterId).log
queue fold in holdout,00,01,02,03,04,05,06,07,08,09
