universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_jannis_fancy_sampling.sh $(seed)
should_transfer_files = NO
request_cpus = 1
request_memory = 16GB
request_disk = 2GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && (TARGET.GPUs_GlobalMemoryMb >= 16000)
output = results/experiment_3_sampling/condor/seed$(seed).$(ClusterId).out
error = results/experiment_3_sampling/condor/seed$(seed).$(ClusterId).err
log = results/experiment_3_sampling/condor/jobs.$(ClusterId).log
queue seed in 42,43,44,45,46
