universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_learning_curve_plot.sh
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 0
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de")
output = results/learning_curves_cgre_cv10/condor/plot.$(ClusterId).out
error = results/learning_curves_cgre_cv10/condor/plot.$(ClusterId).err
log = results/learning_curves_cgre_cv10/condor/plot.$(ClusterId).log
queue 1
