universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_learning_curve.sh
arguments = $(source) $(fold) $(model) cuda
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && ((TARGET.GPUs_GlobalMemoryMb >= 30000) || (TARGET.GPUs_DeviceName == "NVIDIA GeForce RTX 2080 Ti"))
output = results/learning_curves_cgre_cv10/condor/$(source)_$(fold)_$(model).$(ClusterId).$(ProcId).out
error = results/learning_curves_cgre_cv10/condor/$(source)_$(fold)_$(model).$(ClusterId).$(ProcId).err
log = results/learning_curves_cgre_cv10/condor/gpu.$(ClusterId).log
queue source,fold,model from results/learning_curves_cgre_cv10/cuda_jobs.txt
