universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_paper_reproduction.sh $(model) cpu
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
output = results/paper_reproduction_cgre_80_20/condor/$(model).$(ClusterId).$(ProcId).out
error = results/paper_reproduction_cgre_80_20/condor/$(model).$(ClusterId).$(ProcId).err
log = results/paper_reproduction_cgre_80_20/condor/cpu.$(ClusterId).log
queue model in aubin_1_10_1, mlp_small, mlp_deep
