universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_paper_reproduction.sh $(model) cuda $(seed)
should_transfer_files = NO
request_cpus = 1
request_memory = 10GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && (TARGET.GPUs_GlobalMemoryMb >= 16000)
output = results/paper_reproduction_cgre_80_20/condor/$(model).seed$(seed).$(ClusterId).$(ProcId).out
error = results/paper_reproduction_cgre_80_20/condor/$(model).seed$(seed).$(ClusterId).$(ProcId).err
log = results/paper_reproduction_cgre_80_20/condor/multiseed_gpu.$(ClusterId).log
queue model,seed from (
CNN_Jannis_OHE 43
CNN_Jannis_ESM 43
CNN_Jannis_OHE 44
CNN_Jannis_ESM 44
CNN_Jannis_OHE 45
CNN_Jannis_ESM 45
CNN_Jannis_OHE 46
CNN_Jannis_ESM 46
)
