universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_reference_timing.sh
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 0
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de")
output = results/esm_cgreGFP/condor/reference_timing.$(ClusterId).out
error = results/esm_cgreGFP/condor/reference_timing.$(ClusterId).err
log = results/esm_cgreGFP/condor/reference_timing.$(ClusterId).log
queue 1
