universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_target_adaptation_cnn.sh peaks $(Process)
should_transfer_files = NO
request_cpus = 2
request_gpus = 1
request_memory = 12GB
request_disk = 4GB
output = results/target_adaptation_peaks_cnn_seed42_46/condor/gpu.$(ClusterId).$(Process).out
error = results/target_adaptation_peaks_cnn_seed42_46/condor/gpu.$(ClusterId).$(Process).err
log = results/target_adaptation_peaks_cnn_seed42_46/condor/gpu.$(ClusterId).log
queue 10
