universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_transfer_model.sh
arguments = $(mix) $(seed) $(model) cpu
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 0
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de")
output = results/transfer_cgreGFP_seed42_44/condor/$(mix)_$(seed)_$(model).$(ClusterId).out
error = results/transfer_cgreGFP_seed42_44/condor/$(mix)_$(seed)_$(model).$(ClusterId).err
log = results/transfer_cgreGFP_seed42_44/condor/onehot.$(ClusterId).log
queue mix,seed,model from condor/transfer_onehot_jobs.txt
