universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_5seed_finish.sh
should_transfer_files = NO
request_cpus = 1
request_memory = 2GB
request_disk = 1GB
output = results/transfer_cgreGFP_seed42_46_runs/condor/finish.$(ClusterId).out
error = results/transfer_cgreGFP_seed42_46_runs/condor/finish.$(ClusterId).err
log = results/transfer_cgreGFP_seed42_46_runs/condor/finish.$(ClusterId).log
+MaxRuntime = 176400
queue 1
