universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_random_linear_finish.sh
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
output = results/transfer_random_linear_cgreGFP_seed42_46/condor/finish.$(ClusterId).out
error = results/transfer_random_linear_cgreGFP_seed42_46/condor/finish.$(ClusterId).err
log = results/transfer_random_linear_cgreGFP_seed42_46/condor/finish.$(ClusterId).log
queue 1
