universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /nethome/akolchina/gfp_project/condor/run_transfer_model.sh
arguments = $(mix) $(seed) CNN_Jannis cuda
should_transfer_files = NO
request_cpus = 1
request_memory = 18GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && ((TARGET.GPUs_GlobalMemoryMb >= 30000) || (TARGET.GPUs_DeviceName == "NVIDIA GeForce RTX 2080 Ti"))
output = results/transfer_cgreGFP_seed42_44/condor/$(mix)_$(seed)_CNN_Jannis.$(ClusterId).out
error = results/transfer_cgreGFP_seed42_44/condor/$(mix)_$(seed)_CNN_Jannis.$(ClusterId).err
log = results/transfer_cgreGFP_seed42_44/condor/cnn.$(ClusterId).log
queue mix,seed from condor/transfer_cnn_jobs.txt
