universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_random_cpu_models.sh $(Process)
should_transfer_files = NO
request_cpus = 1
request_memory = 8GB
request_disk = 2GB
output = results/transfer_random_cpu_models_condor/cpu.$(ClusterId).$(Process).out
error = results/transfer_random_cpu_models_condor/cpu.$(ClusterId).$(Process).err
log = results/transfer_random_cpu_models_condor/cpu.$(ClusterId).log
queue 80
