universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_5seed_onehot.sh $(Process)
should_transfer_files = NO
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
request_gpus = 0
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de")
output = results/transfer_cgreGFP_seed42_46_runs/condor/onehot.$(ClusterId).$(Process).out
error = results/transfer_cgreGFP_seed42_46_runs/condor/onehot.$(ClusterId).$(Process).err
log = results/transfer_cgreGFP_seed42_46_runs/condor/onehot.$(ClusterId).log
queue 120
