universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_5seed_cnn.sh $(Process)
should_transfer_files = NO
request_cpus = 1
request_memory = 12GB
request_disk = 1GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && (TARGET.GPUs_GlobalMemoryMb >= 16000)
output = results/transfer_cgreGFP_seed42_46_runs/condor/cnn.$(ClusterId).$(Process).out
error = results/transfer_cgreGFP_seed42_46_runs/condor/cnn.$(ClusterId).$(Process).err
log = results/transfer_cgreGFP_seed42_46_runs/condor/cnn.$(ClusterId).log
queue 40
