universe = vanilla
initialdir = /nethome/akolchina/gfp_project
executable = /bin/bash
arguments = condor/run_transfer_al_gpu.sh $(Process)
should_transfer_files = NO
request_cpus = 1
request_memory = 16GB
request_disk = 2GB
request_gpus = 1
requirements = (TARGET.UidDomain == "lsv.uni-saarland.de") && (TARGET.GPUs_GlobalMemoryMb >= 10000)
output = results/transfer_al_cgreGFP_seed42_46/condor/gpu.$(ClusterId).$(Process).out
error = results/transfer_al_cgreGFP_seed42_46/condor/gpu.$(ClusterId).$(Process).err
log = results/transfer_al_cgreGFP_seed42_46/condor/gpu.$(ClusterId).log
queue 40
